#!/bin/sh
set -x -e
###
# Adding curl
###
apk add --no-cache curl
###
# Installing terraform
###
curl https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip > terraform_${TERRAFORM_VERSION}_linux_amd64.zip
unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /bin
###
# Cleaning image
###
rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip
apk del curl
###
# Installing ca-certificates as dependency of terraform
###
apk add --no-cache \
  ca-certificates=${CACERTIFICATES_VERSION} \
  git=${GIT_VERSION} \
  openssh=${OPENSSH_VERSION}
