#!/bin/sh
set -x -eo pipefail

###
# Adding curl
###

apk add --no-cache curl

###
# Installing terraform and it's providers
###

curl -sSLo /resources/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
  https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

unzip /resources/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin

###
# Cleaning image
###

apk del curl

###
# Installing ca-certificates as dependency of terraform
###

apk add --no-cache \
  ca-certificates=${CACERTIFICATES_VERSION} \
  git=${GIT_VERSION} \
  openssh=${OPENSSH_VERSION}
